parameters:
  Artifacts: []
  TestPipeline: false
  ArtifactName: 'not-specified'
  DependsOn: Build
  Registry: 'https://registry.npmjs.org/'
  PrivateRegistry: 'https://pkgs.dev.azure.com/azure-sdk/internal/_packaging/azure-sdk-for-js-pr/npm/registry/'
  TargetDocRepoOwner: ''
  TargetDocRepoName: ''
  ServiceDirectory: ''

stages:
  - ${{if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'))}}:
    - ${{ each artifact in parameters.Artifacts }}:
      - stage: Release_${{artifact.safeName}}
        displayName: 'Release: ${{artifact.name}}'
        dependsOn: ${{parameters.DependsOn}}
        condition: and(succeeded(), ne(variables['SetDevVersion'], 'true'), ne(variables['Skip.Release'], 'true'), ne(variables['Build.Repository.Name'], 'Azure/azure-sdk-for-js-pr'))
        jobs:
          - ${{if ne(artifact.skipPublishDocMs, 'true')}}:
            - deployment: PublishDocs
              displayName: Docs.MS Release
              condition: and(succeeded(), ne(variables['Skip.PublishDocs'], 'true'))
              environment: githubio
              dependsOn: PublishPackage

              pool:
                name: azsdk-pool-mms-ubuntu-2004-general
                vmImage: MMSUbuntu20.04

              strategy:
                runOnce:
                  deploy:
                    steps:
                      - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
                        parameters:
                          SkipDefaultCheckout: true 
                          Paths:
                            - sdk/**/*.md
                      - download: current
                      - template: /eng/common/pipelines/templates/steps/update-docsms-metadata.yml
                        parameters:
                          PackageInfoLocations: 
                            - $(Pipeline.Workspace)/${{parameters.ArtifactName}}/PackageInfo/${{artifact.name}}.json
                          RepoId: Azure/azure-sdk-for-js
                          WorkingDirectory: $(System.DefaultWorkingDirectory)
                          TargetDocRepoOwner: ${{parameters.TargetDocRepoOwner}}
                          TargetDocRepoName: ${{parameters.TargetDocRepoName}}
                          Language: 'javascript'
                          SparseCheckoutPaths:
                            - docs-ref-services/
                            - metadata/
