trigger: none

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      PackageName: "@azure/service-bus"
      ServiceDirectory: servicebus
      MatrixFilters:
        - Pool=.*-ubuntu-.*
      TimeoutInMinutes: 90
      Clouds: 'Public'
      SupportedClouds: 'Public,UsGov,China'
      EnvVars:
        AZURE_CLIENT_ID: $(SERVICEBUS_CLIENT_ID)
        AZURE_TENANT_ID: $(SERVICEBUS_TENANT_ID)
        AZURE_CLIENT_SECRET: $(SERVICEBUS_CLIENT_SECRET)
        AZURE_SUBSCRIPTION_ID: $(SERVICEBUS_SUBSCRIPTION_ID)
